<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Created by UB Development and Alumni Relations.  Updated on Tuesday July 15th 2025 11:00:02 AM -->
<!DOCTYPE country [
	<!ELEMENT country (country_code, short_desc)>
		<!ELEMENT country_code (#PCDATA)>
		<!ELEMENT short_desc (#PCDATA)>
]>
<countrys>
<country>
<country_code>AFG</country_code>
<short_desc>Afghanistan</short_desc>
</country>
<country>
<country_code>ALA</country_code>
<short_desc>Aland Islands</short_desc>
</country>
<country>
<country_code>ALB</country_code>
<short_desc>Albania</short_desc>
</country>
<country>
<country_code>DZA</country_code>
<short_desc>Algeria</short_desc>
</country>
<country>
<country_code>AND</country_code>
<short_desc>Andorra</short_desc>
</country>
<country>
<country_code>AGO</country_code>
<short_desc>Angola</short_desc>
</country>
<country>
<country_code>AIA</country_code>
<short_desc>Anguilla</short_desc>
</country>
<country>
<country_code>ATA</country_code>
<short_desc>Antarctica</short_desc>
</country>
<country>
<country_code>ATG</country_code>
<short_desc>Antigua and Barbuda</short_desc>
</country>
<country>
<country_code>ARG</country_code>
<short_desc>Argentina</short_desc>
</country>
<country>
<country_code>ARM</country_code>
<short_desc>Armenia</short_desc>
</country>
<country>
<country_code>ABW</country_code>
<short_desc>Aruba</short_desc>
</country>
<country>
<country_code>AUS</country_code>
<short_desc>Australia</short_desc>
</country>
<country>
<country_code>AUT</country_code>
<short_desc>Austria</short_desc>
</country>
<country>
<country_code>AZE</country_code>
<short_desc>Azerbaijan</short_desc>
</country>
<country>
<country_code>BHS</country_code>
<short_desc>Bahamas</short_desc>
</country>
<country>
<country_code>BHR</country_code>
<short_desc>Bahrain</short_desc>
</country>
<country>
<country_code>BGD</country_code>
<short_desc>Bangladesh</short_desc>
</country>
<country>
<country_code>BRB</country_code>
<short_desc>Barbados</short_desc>
</country>
<country>
<country_code>BLR</country_code>
<short_desc>Belarus</short_desc>
</country>
<country>
<country_code>BEL</country_code>
<short_desc>Belgium</short_desc>
</country>
<country>
<country_code>BLZ</country_code>
<short_desc>Belize</short_desc>
</country>
<country>
<country_code>BEN</country_code>
<short_desc>Benin</short_desc>
</country>
<country>
<country_code>BMU</country_code>
<short_desc>Bermuda</short_desc>
</country>
<country>
<country_code>BTN</country_code>
<short_desc>Bhutan</short_desc>
</country>
<country>
<country_code>BOL</country_code>
<short_desc>Bolivia</short_desc>
</country>
<country>
<country_code>BIH</country_code>
<short_desc>Bosnia and Herzegovina</short_desc>
</country>
<country>
<country_code>BWA</country_code>
<short_desc>Botswana</short_desc>
</country>
<country>
<country_code>BVT</country_code>
<short_desc>Bouvet Island</short_desc>
</country>
<country>
<country_code>BRA</country_code>
<short_desc>Brazil</short_desc>
</country>
<country>
<country_code>IOT</country_code>
<short_desc>British Indian Ocean Territory</short_desc>
</country>
<country>
<country_code>BRN</country_code>
<short_desc>Brunei Darussalam</short_desc>
</country>
<country>
<country_code>BGR</country_code>
<short_desc>Bulgaria</short_desc>
</country>
<country>
<country_code>BFA</country_code>
<short_desc>Burkina Faso</short_desc>
</country>
<country>
<country_code>BDI</country_code>
<short_desc>Burundi</short_desc>
</country>
<country>
<country_code>KHM</country_code>
<short_desc>Cambodia</short_desc>
</country>
<country>
<country_code>CMR</country_code>
<short_desc>Cameroon</short_desc>
</country>
<country>
<country_code>CAN</country_code>
<short_desc>Canada</short_desc>
</country>
<country>
<country_code>CPV</country_code>
<short_desc>Cape Verde</short_desc>
</country>
<country>
<country_code>CYM</country_code>
<short_desc>Cayman Islands</short_desc>
</country>
<country>
<country_code>CAF</country_code>
<short_desc>Central African Republic</short_desc>
</country>
<country>
<country_code>TCD</country_code>
<short_desc>Chad</short_desc>
</country>
<country>
<country_code>CHL</country_code>
<short_desc>Chile</short_desc>
</country>
<country>
<country_code>CHN</country_code>
<short_desc>China</short_desc>
</country>
<country>
<country_code>CXR</country_code>
<short_desc>Christmas Island</short_desc>
</country>
<country>
<country_code>CCK</country_code>
<short_desc>Cocos (Keeling) Islands</short_desc>
</country>
<country>
<country_code>COL</country_code>
<short_desc>Colombia</short_desc>
</country>
<country>
<country_code>COM</country_code>
<short_desc>Comoros</short_desc>
</country>
<country>
<country_code>COG</country_code>
<short_desc>Congo</short_desc>
</country>
<country>
<country_code>COK</country_code>
<short_desc>Cook Islands</short_desc>
</country>
<country>
<country_code>CRI</country_code>
<short_desc>Costa Rica</short_desc>
</country>
<country>
<country_code>CIV</country_code>
<short_desc>Cote D'Ivoire</short_desc>
</country>
<country>
<country_code>HRV</country_code>
<short_desc>Croatia</short_desc>
</country>
<country>
<country_code>CUB</country_code>
<short_desc>Cuba</short_desc>
</country>
<country>
<country_code>CYP</country_code>
<short_desc>Cyprus</short_desc>
</country>
<country>
<country_code>CZE</country_code>
<short_desc>Czech Republic</short_desc>
</country>
<country>
<country_code>PRK</country_code>
<short_desc>Democratic People's Republic of Korea</short_desc>
</country>
<country>
<country_code>DNK</country_code>
<short_desc>Denmark</short_desc>
</country>
<country>
<country_code>DJI</country_code>
<short_desc>Djibouti</short_desc>
</country>
<country>
<country_code>DMA</country_code>
<short_desc>Dominica</short_desc>
</country>
<country>
<country_code>DOM</country_code>
<short_desc>Dominican Republic</short_desc>
</country>
<country>
<country_code>TLS</country_code>
<short_desc>East Timor</short_desc>
</country>
<country>
<country_code>ECU</country_code>
<short_desc>Ecuador</short_desc>
</country>
<country>
<country_code>EGY</country_code>
<short_desc>Egypt</short_desc>
</country>
<country>
<country_code>SLV</country_code>
<short_desc>El Salvador</short_desc>
</country>
<country>
<country_code>ENG</country_code>
<short_desc>England</short_desc>
</country>
<country>
<country_code>GNQ</country_code>
<short_desc>Equatorial Guinea</short_desc>
</country>
<country>
<country_code>ERI</country_code>
<short_desc>Eritrea</short_desc>
</country>
<country>
<country_code>EST</country_code>
<short_desc>Estonia</short_desc>
</country>
<country>
<country_code>ETH</country_code>
<short_desc>Ethiopia</short_desc>
</country>
<country>
<country_code>FLK</country_code>
<short_desc>Falkland Islands (Malvinas)</short_desc>
</country>
<country>
<country_code>FRO</country_code>
<short_desc>Faroe Islands</short_desc>
</country>
<country>
<country_code>FSM</country_code>
<short_desc>Federated States of Micronesia</short_desc>
</country>
<country>
<country_code>FJI</country_code>
<short_desc>Fiji</short_desc>
</country>
<country>
<country_code>FIN</country_code>
<short_desc>Finland</short_desc>
</country>
<country>
<country_code>FRA</country_code>
<short_desc>France</short_desc>
</country>
<country>
<country_code>GUF</country_code>
<short_desc>French Guiana</short_desc>
</country>
<country>
<country_code>PYF</country_code>
<short_desc>French Polynesia</short_desc>
</country>
<country>
<country_code>ATF</country_code>
<short_desc>French Southern Territories</short_desc>
</country>
<country>
<country_code>GAB</country_code>
<short_desc>Gabon</short_desc>
</country>
<country>
<country_code>GMB</country_code>
<short_desc>Gambia</short_desc>
</country>
<country>
<country_code>GEO</country_code>
<short_desc>Georgia</short_desc>
</country>
<country>
<country_code>DEU</country_code>
<short_desc>Germany</short_desc>
</country>
<country>
<country_code>GHA</country_code>
<short_desc>Ghana</short_desc>
</country>
<country>
<country_code>GIB</country_code>
<short_desc>Gilbraltar</short_desc>
</country>
<country>
<country_code>GRC</country_code>
<short_desc>Greece</short_desc>
</country>
<country>
<country_code>GRL</country_code>
<short_desc>Greenland</short_desc>
</country>
<country>
<country_code>GRD</country_code>
<short_desc>Grenada</short_desc>
</country>
<country>
<country_code>GLP</country_code>
<short_desc>Guadeloupe</short_desc>
</country>
<country>
<country_code>GTM</country_code>
<short_desc>Guatemala</short_desc>
</country>
<country>
<country_code>GGY</country_code>
<short_desc>Guernsey</short_desc>
</country>
<country>
<country_code>GIN</country_code>
<short_desc>Guinea</short_desc>
</country>
<country>
<country_code>GNB</country_code>
<short_desc>Guinea-Bissau</short_desc>
</country>
<country>
<country_code>GUY</country_code>
<short_desc>Guyana</short_desc>
</country>
<country>
<country_code>HTI</country_code>
<short_desc>Haiti</short_desc>
</country>
<country>
<country_code>HMD</country_code>
<short_desc>Heard and McDonald Islands</short_desc>
</country>
<country>
<country_code>VAT</country_code>
<short_desc>Holy See (Vatican City State)</short_desc>
</country>
<country>
<country_code>HND</country_code>
<short_desc>Honduras</short_desc>
</country>
<country>
<country_code>HKG</country_code>
<short_desc>Hong Kong</short_desc>
</country>
<country>
<country_code>HQX</country_code>
<short_desc>Howland Island</short_desc>
</country>
<country>
<country_code>HUN</country_code>
<short_desc>Hungary</short_desc>
</country>
<country>
<country_code>ISL</country_code>
<short_desc>Iceland</short_desc>
</country>
<country>
<country_code>IND</country_code>
<short_desc>India</short_desc>
</country>
<country>
<country_code>IDN</country_code>
<short_desc>Indonesia</short_desc>
</country>
<country>
<country_code>IRN</country_code>
<short_desc>Iran (Islamic Republic Of)</short_desc>
</country>
<country>
<country_code>IRQ</country_code>
<short_desc>Iraq</short_desc>
</country>
<country>
<country_code>IRL</country_code>
<short_desc>Ireland</short_desc>
</country>
<country>
<country_code>IMN</country_code>
<short_desc>Isle of Man</short_desc>
</country>
<country>
<country_code>ISR</country_code>
<short_desc>Israel</short_desc>
</country>
<country>
<country_code>ITA</country_code>
<short_desc>Italy</short_desc>
</country>
<country>
<country_code>JAM</country_code>
<short_desc>Jamaica</short_desc>
</country>
<country>
<country_code>JPN</country_code>
<short_desc>Japan</short_desc>
</country>
<country>
<country_code>JEY</country_code>
<short_desc>Jersey</short_desc>
</country>
<country>
<country_code>JOR</country_code>
<short_desc>Jordan</short_desc>
</country>
<country>
<country_code>KAZ</country_code>
<short_desc>Kazakhstan</short_desc>
</country>
<country>
<country_code>KEN</country_code>
<short_desc>Kenya</short_desc>
</country>
<country>
<country_code>KIR</country_code>
<short_desc>Kiribati</short_desc>
</country>
<country>
<country_code>KOS</country_code>
<short_desc>Kosovo</short_desc>
</country>
<country>
<country_code>KWT</country_code>
<short_desc>Kuwait</short_desc>
</country>
<country>
<country_code>KGZ</country_code>
<short_desc>Kyrgyzstan</short_desc>
</country>
<country>
<country_code>LAO</country_code>
<short_desc>Lao People's Democratic Republic</short_desc>
</country>
<country>
<country_code>LVA</country_code>
<short_desc>Latvia</short_desc>
</country>
<country>
<country_code>LBN</country_code>
<short_desc>Lebanon</short_desc>
</country>
<country>
<country_code>LSO</country_code>
<short_desc>Lesotho</short_desc>
</country>
<country>
<country_code>LBR</country_code>
<short_desc>Liberia</short_desc>
</country>
<country>
<country_code>LBY</country_code>
<short_desc>Libya</short_desc>
</country>
<country>
<country_code>LIE</country_code>
<short_desc>Liechtenstein</short_desc>
</country>
<country>
<country_code>LTU</country_code>
<short_desc>Lithuania</short_desc>
</country>
<country>
<country_code>LUX</country_code>
<short_desc>Luxembourg</short_desc>
</country>
<country>
<country_code>MAC</country_code>
<short_desc>Macau</short_desc>
</country>
<country>
<country_code>MDG</country_code>
<short_desc>Madagascar</short_desc>
</country>
<country>
<country_code>MWI</country_code>
<short_desc>Malawi</short_desc>
</country>
<country>
<country_code>MYS</country_code>
<short_desc>Malaysia</short_desc>
</country>
<country>
<country_code>MDV</country_code>
<short_desc>Maldives</short_desc>
</country>
<country>
<country_code>MLI</country_code>
<short_desc>Mali</short_desc>
</country>
<country>
<country_code>MLT</country_code>
<short_desc>Malta</short_desc>
</country>
<country>
<country_code>MHL</country_code>
<short_desc>Marshall Islands</short_desc>
</country>
<country>
<country_code>MTQ</country_code>
<short_desc>Martinique</short_desc>
</country>
<country>
<country_code>MRT</country_code>
<short_desc>Mauritania</short_desc>
</country>
<country>
<country_code>MUS</country_code>
<short_desc>Mauritius</short_desc>
</country>
<country>
<country_code>MYT</country_code>
<short_desc>Mayotte</short_desc>
</country>
<country>
<country_code>MEX</country_code>
<short_desc>Mexico</short_desc>
</country>
<country>
<country_code>MCO</country_code>
<short_desc>Monaco</short_desc>
</country>
<country>
<country_code>MNG</country_code>
<short_desc>Mongolia</short_desc>
</country>
<country>
<country_code>MSR</country_code>
<short_desc>Montserrat</short_desc>
</country>
<country>
<country_code>MAR</country_code>
<short_desc>Morocco</short_desc>
</country>
<country>
<country_code>MOZ</country_code>
<short_desc>Mozambique</short_desc>
</country>
<country>
<country_code>MMR</country_code>
<short_desc>Myanmar (Burma)</short_desc>
</country>
<country>
<country_code>NAM</country_code>
<short_desc>Namibia</short_desc>
</country>
<country>
<country_code>NRU</country_code>
<short_desc>Nauru</short_desc>
</country>
<country>
<country_code>NPL</country_code>
<short_desc>Nepal</short_desc>
</country>
<country>
<country_code>NLD</country_code>
<short_desc>Netherlands</short_desc>
</country>
<country>
<country_code>ANT</country_code>
<short_desc>Netherlands Antilles</short_desc>
</country>
<country>
<country_code>NCL</country_code>
<short_desc>New Caledonia</short_desc>
</country>
<country>
<country_code>NZL</country_code>
<short_desc>New Zealand</short_desc>
</country>
<country>
<country_code>NIC</country_code>
<short_desc>Nicaragua</short_desc>
</country>
<country>
<country_code>NER</country_code>
<short_desc>Niger</short_desc>
</country>
<country>
<country_code>NGA</country_code>
<short_desc>Nigeria</short_desc>
</country>
<country>
<country_code>NIU</country_code>
<short_desc>Niue</short_desc>
</country>
<country>
<country_code>NFK</country_code>
<short_desc>Norfolk Island</short_desc>
</country>
<country>
<country_code>NIR</country_code>
<short_desc>Northern Ireland</short_desc>
</country>
<country>
<country_code>NOR</country_code>
<short_desc>Norway</short_desc>
</country>
<country>
<country_code>NAP</country_code>
<short_desc>Not Applicable</short_desc>
</country>
<country>
<country_code>NRE</country_code>
<short_desc>Not Reported</short_desc>
</country>
<country>
<country_code>OMN</country_code>
<short_desc>Oman</short_desc>
</country>
<country>
<country_code>PAK</country_code>
<short_desc>Pakistan</short_desc>
</country>
<country>
<country_code>PLW</country_code>
<short_desc>Palau</short_desc>
</country>
<country>
<country_code>PSE</country_code>
<short_desc>Palestinian Territory</short_desc>
</country>
<country>
<country_code>PAN</country_code>
<short_desc>Panama</short_desc>
</country>
<country>
<country_code>PNG</country_code>
<short_desc>Papua New Guinea</short_desc>
</country>
<country>
<country_code>PRY</country_code>
<short_desc>Paraguay</short_desc>
</country>
<country>
<country_code>PER</country_code>
<short_desc>Peru</short_desc>
</country>
<country>
<country_code>PHL</country_code>
<short_desc>Philippines</short_desc>
</country>
<country>
<country_code>PCN</country_code>
<short_desc>Pitcairn Islands</short_desc>
</country>
<country>
<country_code>POL</country_code>
<short_desc>Poland</short_desc>
</country>
<country>
<country_code>PRT</country_code>
<short_desc>Portugal</short_desc>
</country>
<country>
<country_code>QAT</country_code>
<short_desc>Qatar</short_desc>
</country>
<country>
<country_code>KOR</country_code>
<short_desc>Republic of Korea</short_desc>
</country>
<country>
<country_code>MDA</country_code>
<short_desc>Republic of Moldova</short_desc>
</country>
<country>
<country_code>MNE</country_code>
<short_desc>Republic of Montenegro</short_desc>
</country>
<country>
<country_code>MKD</country_code>
<short_desc>Republic of North Macedonia</short_desc>
</country>
<country>
<country_code>REU</country_code>
<short_desc>Reunion</short_desc>
</country>
<country>
<country_code>ROU</country_code>
<short_desc>Romania</short_desc>
</country>
<country>
<country_code>RUS</country_code>
<short_desc>Russia</short_desc>
</country>
<country>
<country_code>RWA</country_code>
<short_desc>Rwanda</short_desc>
</country>
<country>
<country_code>BLM</country_code>
<short_desc>Saint Barthelemy</short_desc>
</country>
<country>
<country_code>SHN</country_code>
<short_desc>Saint Helena</short_desc>
</country>
<country>
<country_code>KNA</country_code>
<short_desc>Saint Kitts and Nevis</short_desc>
</country>
<country>
<country_code>LCA</country_code>
<short_desc>Saint Lucia</short_desc>
</country>
<country>
<country_code>MAF</country_code>
<short_desc>Saint Martin</short_desc>
</country>
<country>
<country_code>SPM</country_code>
<short_desc>Saint Pierre and Miquelon</short_desc>
</country>
<country>
<country_code>WSM</country_code>
<short_desc>Samona</short_desc>
</country>
<country>
<country_code>SMR</country_code>
<short_desc>San Marino</short_desc>
</country>
<country>
<country_code>STP</country_code>
<short_desc>Sao Tome and Principe</short_desc>
</country>
<country>
<country_code>SAU</country_code>
<short_desc>Saudi Arabia</short_desc>
</country>
<country>
<country_code>SCT</country_code>
<short_desc>Scotland</short_desc>
</country>
<country>
<country_code>SEN</country_code>
<short_desc>Senegal</short_desc>
</country>
<country>
<country_code>SRB</country_code>
<short_desc>Serbia</short_desc>
</country>
<country>
<country_code>SYC</country_code>
<short_desc>Seychelles</short_desc>
</country>
<country>
<country_code>SLE</country_code>
<short_desc>Sierra Leone</short_desc>
</country>
<country>
<country_code>SGP</country_code>
<short_desc>Singapore</short_desc>
</country>
<country>
<country_code>SVK</country_code>
<short_desc>Slovakia</short_desc>
</country>
<country>
<country_code>SVN</country_code>
<short_desc>Slovenia</short_desc>
</country>
<country>
<country_code>SLB</country_code>
<short_desc>Solomon Islands</short_desc>
</country>
<country>
<country_code>SOM</country_code>
<short_desc>Somalia</short_desc>
</country>
<country>
<country_code>ZAF</country_code>
<short_desc>South Africa</short_desc>
</country>
<country>
<country_code>ESP</country_code>
<short_desc>Spain</short_desc>
</country>
<country>
<country_code>LKA</country_code>
<short_desc>Sri Lanka</short_desc>
</country>
<country>
<country_code>VCT</country_code>
<short_desc>St. Vincent and The Grenadines</short_desc>
</country>
<country>
<country_code>SGS</country_code>
<short_desc>Sth Georgia &amp; Sth Sandwich Is</short_desc>
</country>
<country>
<country_code>SDN</country_code>
<short_desc>Sudan</short_desc>
</country>
<country>
<country_code>SUR</country_code>
<short_desc>Suriname</short_desc>
</country>
<country>
<country_code>SJM</country_code>
<short_desc>Svalbard and Jan Mayen</short_desc>
</country>
<country>
<country_code>SWZ</country_code>
<short_desc>Swaziland</short_desc>
</country>
<country>
<country_code>SWE</country_code>
<short_desc>Sweden</short_desc>
</country>
<country>
<country_code>CHE</country_code>
<short_desc>Switzerland</short_desc>
</country>
<country>
<country_code>SYR</country_code>
<short_desc>Syrian Arab Republic</short_desc>
</country>
<country>
<country_code>TWN</country_code>
<short_desc>Taiwan</short_desc>
</country>
<country>
<country_code>TJK</country_code>
<short_desc>Tajikistan</short_desc>
</country>
<country>
<country_code>THA</country_code>
<short_desc>Thailand</short_desc>
</country>
<country>
<country_code>COD</country_code>
<short_desc>The Democratic Republic of the Congo</short_desc>
</country>
<country>
<country_code>TGO</country_code>
<short_desc>Togo</short_desc>
</country>
<country>
<country_code>TKL</country_code>
<short_desc>Tokelau</short_desc>
</country>
<country>
<country_code>TON</country_code>
<short_desc>Tonga</short_desc>
</country>
<country>
<country_code>TTO</country_code>
<short_desc>Trinidad and Tobago</short_desc>
</country>
<country>
<country_code>TUN</country_code>
<short_desc>Tunisia</short_desc>
</country>
<country>
<country_code>TUR</country_code>
<short_desc>Turkey</short_desc>
</country>
<country>
<country_code>TKM</country_code>
<short_desc>Turkmenistan</short_desc>
</country>
<country>
<country_code>TCA</country_code>
<short_desc>Turks and Caicos Islands</short_desc>
</country>
<country>
<country_code>TUV</country_code>
<short_desc>Tuvalu</short_desc>
</country>
<country>
<country_code>UMI</country_code>
<short_desc>US Minor Outlying Islands</short_desc>
</country>
<country>
<country_code>UGA</country_code>
<short_desc>Uganda</short_desc>
</country>
<country>
<country_code>UKR</country_code>
<short_desc>Ukraine</short_desc>
</country>
<country>
<country_code>ARE</country_code>
<short_desc>United Arab Emirates</short_desc>
</country>
<country>
<country_code>GBR</country_code>
<short_desc>United Kingdom</short_desc>
</country>
<country>
<country_code>TZA</country_code>
<short_desc>United Republic of Tanzania</short_desc>
</country>
<country>
<country_code>USA</country_code>
<short_desc>United States</short_desc>
</country>
<country>
<country_code>USP</country_code>
<short_desc>United States Misc. Pacific Islands</short_desc>
</country>
<country>
<country_code>URY</country_code>
<short_desc>Uruguay</short_desc>
</country>
<country>
<country_code>UZB</country_code>
<short_desc>Uzbekistan</short_desc>
</country>
<country>
<country_code>VUT</country_code>
<short_desc>Vanuatu</short_desc>
</country>
<country>
<country_code>VEN</country_code>
<short_desc>Venezuela</short_desc>
</country>
<country>
<country_code>VNM</country_code>
<short_desc>Vietnam</short_desc>
</country>
<country>
<country_code>VGB</country_code>
<short_desc>Virgin Islands (British)</short_desc>
</country>
<country>
<country_code>WAL</country_code>
<short_desc>Wales</short_desc>
</country>
<country>
<country_code>WLF</country_code>
<short_desc>Wallis and Futuna Islands</short_desc>
</country>
<country>
<country_code>ESH</country_code>
<short_desc>Western Sahara</short_desc>
</country>
<country>
<country_code>YEM</country_code>
<short_desc>Yemen</short_desc>
</country>
<country>
<country_code>ZMB</country_code>
<short_desc>Zambia</short_desc>
</country>
<country>
<country_code>ZWE</country_code>
<short_desc>Zimbabwe</short_desc>
</country>

</countrys>